# Generated by Django 5.1.6 on 2025-02-18 11:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vasarlo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vezeteknev', models.CharField(max_length=50)),
                ('keresztnev', models.CharField(max_length=50)),
                ('telefonszam', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Termek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
                ('ar', models.IntegerField(default=0)),
                ('leiras', models.TextField(blank=True, default='', max_length=7000, null=True)),
                ('kep', models.ImageField(upload_to='uploads/product/')),
                ('kategoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webshop_app.kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Megrendeles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mennyiseg', models.IntegerField(default=1)),
                ('telefonszam', models.CharField(blank=True, default='', max_length=11)),
                ('cim', models.CharField(blank=True, default='', max_length=200)),
                ('datum', models.DateTimeField(default=datetime.datetime.today)),
                ('statusz', models.BooleanField(default=False)),
                ('termek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop_app.termek')),
                ('vasarlo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop_app.vasarlo')),
            ],
        ),
    ]
