# Generated by Django 5.1.6 on 2025-02-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0002_alter_kategoria_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termek',
            name='kep',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
