# Generated by Django 5.1.6 on 2025-02-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0003_alter_termek_kep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termek',
            name='kep',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
