# Generated by Django 5.1.6 on 2025-02-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0004_alter_termek_kep'),
    ]

    operations = [
        migrations.AddField(
            model_name='termek',
            name='akcios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='termek',
            name='akcios_ar',
            field=models.IntegerField(default=0, max_length=7),
        ),
        migrations.AlterField(
            model_name='termek',
            name='ar',
            field=models.IntegerField(default=0, max_length=7),
        ),
    ]
