# Generated by Django 5.1.6 on 2025-02-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0005_termek_akcios_termek_akcios_ar_alter_termek_ar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoria',
            options={'verbose_name_plural': 'kategoriak'},
        ),
    ]
