# Generated by Django 5.1.6 on 2025-02-24 11:16

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0006_alter_kategoria_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='megrendeles',
            name='telefonszam',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='vasarlo',
            name='telefonszam',
            field=models.CharField(max_length=12),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modositas_datuma', models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User)),
                ('telefon', models.CharField(blank=True, max_length=11)),
                ('cim1', models.CharField(blank=True, max_length=100)),
                ('cim2', models.CharField(blank=True, max_length=100)),
                ('iranyitoszam', models.CharField(blank=True, max_length=4)),
                ('varos', models.CharField(blank=True, max_length=50)),
                ('megye', models.CharField(blank=True, max_length=50)),
                ('felhasznalo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
