# Generated by Django 5.1.6 on 2025-03-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0007_alter_megrendeles_telefonszam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termek',
            name='akcios_ar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='termek',
            name='ar',
            field=models.IntegerField(default=0),
        ),
    ]
