# Generated by Django 5.1.6 on 2025-03-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0008_alter_termek_akcios_ar_alter_termek_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='regikosar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
